# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python

python:
  - 3.6
{% if cookiecutter.use_apistar != 'y' %}
  - 3.5
{% endif %}

install:
  - pip install -U pip pipenv
  - pip install python-coveralls
  - make dev

script:
  - make check
  - make dist
  - make doc
  - make test-unit
  - make test-coverage

after_success:
  coveralls

{% if cookiecutter.use_pypi_deployment_with_travis == 'y' -%}
# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  user: {{ cookiecutter.pypi_username }}
  distributions: sdist bdist_wheel
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: {{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}
{%- endif %}
