language: python

python:
    - "3.5"
    - "3.6"
env:
  - DJANGO_SETTINGS_MODULE=config.local_settings

install:
  - pip install pipenv>=9.0 cookiecutter

script:
  - python test-script.py 
  - cd my_project_name
  - make all