language: python

python:
    - "3.5"
    - "3.6"

install:
  - pip install pipenv>=9.0 cookiecutter

script:
  - pipenv --rm
  - python test-script.py
  - pipenv --rm
  - cd my_project_name
  - make all 